name: Nix (Update Inputs)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update inputs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Update inputs
        run: nix flake update

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[gha] Nix: update inputs"