name: Rebase test branch on master and add a commit

on:
  push:
    branches:
      - master  # Run on every master commit

jobs:
  rebase-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history

      - name: Set up Git
        run: |
          git config user.name "qbisi"
          git config user.email "qbisicwate@gmail.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Rebase test onto stage
        run: |
          git checkout test || git checkout -b test origin/test

          git fetch origin stage
          git rebase origin/stage

          git push origin test --force-with-lease
