name: Rebase test branch on master and add a commit

on:
  push:
    branches:
      - master  # Run on every master commit

permissions:
  contents: write

jobs:
  rebase-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history

      - name: Set up Git
        run: |
          git config user.name "qbisi"
          git config user.email "qbisicwate@gmail.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Rebase ci/test onto stage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout ci/test || git checkout -b ci/test origin/ci/test

          git fetch origin stage
          git rebase origin/stage

          git push origin ci/test --force-with-lease
